services:
  db:
    build:
      context: .
      dockerfile: Dockerfile-mongodb
    container_name: mongodb
    hostname: "${MONGO_HOST}"
    restart: on-failure
    env_file:
      - .env
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DB}
    ports:
      - "${MONGO_PORT}:27017"

  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: build_app
    container_name: fastapi-app
    restart: on-failure
    ports:
      - "${APP_PORT}:8000"
    env_file:
      - .env
    volumes:
      - ./:/app


  redis:
    image: redis:latest
    restart: on-failure
    container_name: redis
    env_file:
      - .env
    ports:
      - "${REDIS_PORT}:6379"

  worker:
    build:
      context: .
      dockerfile: Dockerfile
    command: ['taskiq', 'worker', 'src.taskiq.main:broker', '-fsd']
    container_name: worker
    env_file:
      - .env
    volumes:
      - .:/app

  scheduler:
    build:
      context: .
      dockerfile: Dockerfile
    command: ['taskiq', 'scheduler', 'src.taskiq.main:scheduler', '--skip-first-run']
    container_name: scheduler
    env_file:
      - .env
    volumes:
      - .:/app
